version: '3.7'
services:
  db:
    image: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
  rest_api:
    build: ./rest_api
    command: ./docker-entrypoint.sh
    volumes:
      - ./rest_api:/cah
    depends_on:
      - db
  website:
    build: ./website
    ports:
      - 80:80
    depends_on:
      - rest_api
