# Generated by Django 3.0.3 on 2020-05-31 16:48

import collections
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200511_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deque',
            name='size',
        ),
        migrations.AlterField(
            model_name='deque',
            name='cards',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='deque',
            name='deque',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='items',
            field=picklefield.fields.PickledObjectField(default=collections.deque, editable=False),
        ),
    ]
