# Generated by Django 3.0.7 on 2020-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200531_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
